source 'https://rubygems.org'


gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'bower-rails', "~> 0.9.2"


group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

gem 'coffee-rails', '~> 4.0.0'

gem 'turbolinks'

 gem 'jbuilder', '~> 1.2'
 gem 'sass', '3.2.19' 
group :test, :development do
  gem "rspec"
  gem "rspec-rails", "~> 2.0"
  gem "factory_girl_rails", "~> 4.0"
  gem "capybara"
  gem "database_cleaner"
  gem "selenium-webdriver"
end

 group :doc do
   gem 'sdoc', require: false
end

